-- 会員
CREATE TABLE CUSTOMER (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR2(32 CHAR) NOT NULL,
 -- 読み仮名
	READING VARCHAR2(64 CHAR) NOT NULL,
	PASSWORD VARCHAR2(128) NOT NULL,
	EMAIL VARCHAR2(64 CHAR) NOT NULL,
	DATE_CREATED DATE DEFAULT CURRENT_DATE,
	DELETED NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE CUSTOMER_SEQ NOCACHE;

-- 会員が登録した宛先住所
-- 複数登録可能
CREATE TABLE ADDRESS_PROFILE (
	ID INTEGER PRIMARY KEY,
	CUSTOMER INTEGER REFERENCES CUSTOMER(ID) NOT NULL,
 -- 宛先名
	NAME VARCHAR2(32 CHAR) UNIQUE NOT NULL,
	POST_CODE VARCHAR2(8) NOT NULL,
	ADDRESS VARCHAR2(128 CHAR) NOT NULL,
	PHONE_NUMBER VARCHAR2(11),
	EMAIL VARCHAR2(64 CHAR),
 -- 宛先名
	ADDRESSEE_NAME VARCHAR2(32 CHAR) NOT NULL,
 -- 宛先名読み仮名
	ADDRESSEE_READING VARCHAR2(64 CHAR) NOT NULL,
	DATE_CREATED DATE DEFAULT CURRENT_DATE,
	DELETED NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE ADDRESS_SEQ NOCACHE;

-- 会員の標準宛先
-- address_profileが存在しないままでは作れないので、
-- その作成後に外部参照を追加
ALTER TABLE CUSTOMER ADD MAIN_ADDRESS INTEGER DEFAULT NULL REFERENCES ADDRESS_PROFILE(ID);

-- パン生地の種類
CREATE TABLE BREAD (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR2(32 CHAR) NOT NULL,
 -- 読み仮名
	READING VARCHAR2(64 CHAR) NOT NULL,
	PRICE INTEGER NOT NULL,
	DESCRIPTION VARCHAR2(128 CHAR) NOT NULL,
	IMAGE VARCHAR2(64 CHAR) NOT NULL,
	DATE_CREATED DATE DEFAULT CURRENT_DATE,
	DELETED NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE BREAD_SEQ NOCACHE;

-- クリームの種類
CREATE TABLE CREAM (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR2(32 CHAR) NOT NULL,
 -- 読み仮名
	READING VARCHAR2(64 CHAR) NOT NULL,
	PRICE INTEGER NOT NULL,
	DESCRIPTION VARCHAR2(128 CHAR) NOT NULL,
	IMAGE VARCHAR2(64 CHAR) NOT NULL,
	DATE_CREATED DATE DEFAULT CURRENT_DATE,
	DELETED NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE CREAM_SEQ NOCACHE;

-- 商品
CREATE TABLE ITEM (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR2(32 CHAR) NOT NULL,
 -- 読み仮名
	READING VARCHAR2(64 CHAR) NOT NULL,
	BREAD INTEGER REFERENCES BREAD(ID) NOT NULL,
	DESCRIPTION VARCHAR2(512 CHAR) NOT NULL,
	DELETED NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE ITEM_SEQ NOCACHE;

-- 商品とクリームの関係性
CREATE TABLE ITEM_CREAM (
	ITEM INTEGER REFERENCES ITEM(ID),
	CREAM INTEGER REFERENCES CREAM(ID),
	CONSTRAINT PK_IC PRIMARY KEY (ITEM, CREAM)
);

-- 既存の(店の)商品
CREATE TABLE STORE_ITEM (
	ITEM INTEGER PRIMARY KEY REFERENCES ITEM(ID),
	IMAGE VARCHAR2(64 CHAR) NOT NULL
);

-- 会員のカスタムで作成した商品
CREATE TABLE CUSTOM_ITEM (
	ITEM INTEGER PRIMARY KEY REFERENCES ITEM(ID) NOT NULL,
	CREATOR INTEGER REFERENCES CUSTOMER(ID) NOT NULL,
 -- 公開済か否か
	IS_PUBLIC NUMBER(1) DEFAULT 0
);

-- 会員のお気に入り登録
CREATE TABLE FAVORITE (
	OWNER INTEGER REFERENCES CUSTOMER(ID),
	ITEM INTEGER REFERENCES ITEM(ID),
	CONSTRAINT PK_FAV PRIMARY KEY (OWNER, ITEM)
);

-- クレカ情報の登録
CREATE TABLE CREDIT_CARD (
	ID INTEGER PRIMARY KEY,
	OWNER INTEGER REFERENCES CUSTOMER(ID) NOT NULL,
	NAME VARCHAR2(32 CHAR) NOT NULL,
	HOLDER_NAME VARCHAR2(64) NOT NULL,
	NO VARCHAR2(16) NOT NULL,
	CVC VARCHAR2(3) NOT NULL
);

-- 注文
CREATE TABLE PRODUCT_ORDER (
	ID INTEGER PRIMARY KEY,
	CUSTOMER INTEGER REFERENCES CUSTOMER(ID),
	PAYMENT_METHOD NUMBER(1) NOT NULL CHECK (PAYMENT_METHOD BETWEEN 0 AND 4),
	CREDIT_CARD INTEGER CHECK ((PAYMENT_METHOD = 0 AND CREDIT_CARD IS NOT NULL) OR PAYMENT_METHOD <> 0) REFERENCES CREDIT_CARD(ID),
	DATE_CREATED DATE DEFAULT CURRENT_DATE,
	CANCELLED NUMBER(1) DEFAULT 0,
	ADDRESS INTEGER REFERENCES ADDRESS_PROFILE(ID) NOT NULL,
	OPTIONAL_DETAILS VARCHAR2(512),
	COMPLETED DATE
);

CREATE SEQUENCE ORDER_SEQ NOCACHE;

-- 注文の商品項目
<<<<<<< HEAD
CREATE TABLE product_order_item (
	product_order INTEGER REFERENCES product_order(id) NOT NULL,
	item INTEGER REFERENCES item(id) NOT NULL,
	amount INTEGER CHECK (amount > 0),
	CONSTRAINT pk PRIMARY KEY (product_order, item)
=======
CREATE TABLE PRODUCT_ORDER_ITEM (
	PRODUCT_ORDER INTEGER REFERENCES PRODUCT_ORDER(ID) NOT NULL,
	ITEM INTEGER REFERENCES ITEM(ID) NOT NULL,
	AMOUNT INTEGER CHECK (AMOUNT > 0),
	CONSTRAINT PK PRIMARY KEY (PRODUCT_ORDER, ITEM)
>>>>>>> origin/entity_shion
);

-- 管理者
CREATE TABLE ADMIN (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR2(16 CHAR),
	PASSWORD VARCHAR2(32),
	DATE_CREATED DATE DEFAULT CURRENT_DATE,
	DELETED NUMBER(1) DEFAULT 0,
	SYSTEM NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE ADMIN_SEQ;